version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: ${DOCKERHUB_USERNAME}/controle-financeiro-api:${IMAGE_TAG}
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DB_USERNAME
      - SPRING_DB_PASSWORD
    depends_on:
      - db
  bot:
    build:
      context: .
      dockerfile: ./bot-telegram/Dockerfile
    image: ${DOCKERHUB_USERNAME}/controle-financeiro-bot:${IMAGE_TAG}
    environment:
      - BOT_TOKEN
      - API_URL
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"