on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-docker-img:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set img tag
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build all images with docker compose
        run: docker compose build

      - name: Push API image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/controle-financeiro-api:${IMAGE_TAG}

      - name: Push Bot image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/controle-financeiro-bot:${IMAGE_TAG}